[package]
name = "EliteRustClient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.1"
egui_extras = { version = "0.21.0", features = ["image"] }
image = { version = "0.24.5", features = ["png"] }
#iota-client = { git = "https://github.com/iotaledger/iota.rs", rev = "df302750701667ad28f4830d8bfbb214291036b1" }
#iota-client = { git = "https://github.com/arne-fuchs/iota.rs" }
#iota-wallet = { git = "https://github.com/iotaledger/wallet.rs" }
iota-wallet = "1.0.0-rc.5"
#Stay above 1.22.1 because of security reasons
tokio = { version = "1.26.0", features = ["full"] }
derive = "1.0.0"
json = "0.12.4"
serde_json = "1.0.94"
chrono = "0.4.23"
bus = "2.3.0"
async-recursion = "1.0.2"
rustc-hex = "2.1.0"
bech32 = "0.9.1"

fern-logger = "0.5.0"
log = "0.4.17"
#Text to speech
#tts_rust = "0.3.3"