[package]
name = "edcas-client"
version = "0.3.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/arne-fuchs/edcas-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.27.0", features = ["persistence"] }
egui_extras = { version = "0.27.0", features = ["image"] }
egui_plot = "0.27.0"
image = { version = "0.25.0", features = ["png"] }
tokio = { version = "1.26.0", features = ["full"] }
derive = "1.0.0"
json = "0.12.4"
serde = "1.0.171"
serde_json = "1.0.103"
chrono = "0.4.23"
bus = "2.3.0"
async-recursion = "1.0.2"
rustc-hex = "2.1.0"
bech32 = "0.11.0"
reqwest = "0.12.2"
select = "0.6.0"
sha256 = "1.1.3"
num-format = "0.4.4"
enum-map = { version = "2", features = ["serde"] }
opener = "0.7.0"
lazy_static = "1.4.0"
flate2 = { version = "1.0.25", features = [
  "zlib-ng",
], default-features = false }
base64 = "0.22.0"
ethers = {version = "2.0.14"}

fern-logger = "0.5.0"
log = "0.4.17"

# TUI
ratatui = "0.26.1"
crossterm = "0.27.0"


[build-dependencies]
ethers = {version = "2.0.14"}

# #[cfg(feature = "evm")]
#[features]
#default = ["evm"]
#evm = ["dep:ethers"]
