[package]
name = "edcas-client"
version = "0.3.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/arne-fuchs/edcas-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0" }
egui_extras = { version = "0.22.0", features = ["image"] }
egui_plot = "0.23.0"
image = { version = "0.24.5", features = ["png"] }
#iota-client = { git = "https://github.com/iotaledger/iota.rs", rev = "df302750701667ad28f4830d8bfbb214291036b1" }
#iota-client = { git = "https://github.com/arne-fuchs/iota.rs" }
#iota-wallet = { git = "https://github.com/iotaledger/wallet.rs" }
#iota-wallet = "1.0.0-rc.6"
iota-sdk = { version = "1.0.3", features = [
  "stronghold",
  "rocksdb",
], optional = true }
#Stay above 1.22.1 because of security reasons
tokio = { version = "1.26.0", features = ["full"] }
derive = "1.0.0"
json = "0.12.4"
serde = "1.0.171"
serde_json = "1.0.103"
chrono = "0.4.23"
bus = "2.3.0"
async-recursion = "1.0.2"
rustc-hex = "2.1.0"
bech32 = "0.9.1"
reqwest = "0.11.18"
select = "0.6.0"
sha256 = "1.1.3"
num-format = "0.4.4"
enum-map = { version = "2", features = ["serde"] }
opener = "0.6.1"
lazy_static = "1.4.0"
flate2 = { version = "1.0.25", features = [
  "zlib-ng",
], default-features = false }
base64 = "0.21.2"

fern-logger = "0.5.0"
log = "0.4.17"
#Text to speech
#tts_rust = "0.3.3"

# TUI
ratatui = "0.26.1"
crossterm = "0.27.0"


[features]
default = ["iota"]
iota = ["dep:iota-sdk"]
